// List of pigeon names for random generation
// You can edit these lists to add/remove names as needed

export const maleNames = [
  'Liam', 'Noah', 'Oliver', 'Elijah', 'Mateo', 'Luca', 'Hugo', 'Santiago', 'Diego', 'Rafael', 'Leonardo', 'Enzo', 'Matteo', 'Giovanni', 'Alexandre', 'Louis', 'Antoine', 'Dimitri', 'Ivan', 'Nikolai', 'Alexei', 'Sergey', 'Mohammed', 'Ahmed', 'Omar', 'Youssef', 'Idris', 'Musa', 'Tunde', 'Kwame', 'Obi', 'Chinedu', 'Thabo', 'Sipho', 'Kofi', 'Hiroshi', 'Takumi', 'Haruto', 'Ren', 'Daiki', 'Chen', 'Wei', 'Jun', 'Tao', 'Arun', 'Raj', 'Rohan', 'Vikram', 'Amir', 'Reza', 'Farid', 'Arman', 'Yusuf', 'Mustafa', 'Ayan', 'Zaid', 'Tariq', 'Samir', 'Kevin', 'John', 'James', 'William', 'Robert', 'Charles', 'Jack', 'Harry', 'Alfie', 'George', 'Theo', 'Owen', 'Aiden', 'Connor', 'Cian', 'Ronan', 'Declan', 'Eoin', 'Niall', 'Pedro', 'Tiago', 'Miguel', 'Bruno', 'Carlos', 'Andres', 'Jorge', 'Alonso', 'Esteban', 'Emil', 'Sven', 'Lars', 'Erik', 'Hans', 'Kai', 'Jari', 'Timo', 'Niklas', 'Abiola', 'Adebayo', 'Adekunle', 'Adeniyi', 'Adesanya', 'Adetokunbo', 'Agbaje', 'Agyeman', 'Akande', 'Akintola', 'Amadi', 'Amadou', 'Anibaba', 'Anyanwu', 'Asante', 'Asemota', 'Atangana', 'Ayele', 'Ayodele', 'Azikiwe', 'Babajide', 'Bagayoko', 'Balogun', 'Banda', 'Bankole', 'Barrow', 'Bassey', 'Bello', 'Biko', 'Bongo', 'Chikere', 'Chukwuma', 'Conteh', 'Dada', 'Danjuma', 'Darboe', 'Dlamini', 'Diakite', 'Diallo', 'Diarra', 'Dibba', 'Dikko', 'Doumbia', 'Drame', 'Edeh', 'Eke', 'Ekpo', 'Ekwueme', 'Enahoro', 'Essien', 'Etim', 'Eze', 'Fadipe', 'Fashola', 'Fofana', 'Gbadamosi', 'Gbeho', 'Gichuru', 'Gomwalk', 'Gondo', 'Gyan', 'Hadebe', 'Hlongwane', 'Ibe', 'Ibrahim', 'Igwe', 'Ikenna', 'Iroanya', 'Issaka', 'Jalloh', 'Jibola', 'Kainde', 'Kamara', 'Kasule', 'Kayode', 'Kenyatta', 'Kitenge', 'Koffi', 'Kone', 'Koulibaly', 'Kufuor', 'Laryea', 'Lumumba', 'Madaki', 'Mafela', 'Magasa', 'Mahlangu', 'Makinde', 'Maku', 'Malunga', 'Mamadou', 'Maponya', 'Masuku', 'Matambo', 'Matlaba', 'Mbatha', 'Mbeki', 'Mbombo', 'Mendy'
];

export const femaleNames = [
  'Emma', 'Olivia', 'Ava', 'Sophia', 'Isabella', 'Luna', 'Camila', 'Valentina', 'Martina', 'Emilia', 'Giulia', 'Chiara', 'Sofia', 'Alice', 'Manon', 'Camille', 'Natalia', 'Yulia', 'Daria', 'Irina', 'Katya', 'Fatima', 'Amina', 'Layla', 'Zainab', 'Mariam', 'Ife', 'Ngozi', 'Aisha', 'Abeba', 'Zanele', 'Thuli', 'Ama', 'Akua', 'Sakura', 'Yui', 'Hana', 'Aiko', 'Misaki', 'Li', 'Mei', 'Xiu', 'Lin', 'Ananya', 'Priya', 'Saanvi', 'Kavya', 'Laila', 'Zahra', 'Yasmin', 'Samira', 'Salma', 'Amira', 'Zoya', 'Noor', 'Emily', 'Grace', 'Lily', 'Chloe', 'Ella', 'Evie', 'Poppy', 'Freya', 'Daisy', 'Clara', 'Beatriz', 'Ines', 'Leonor', 'Francisca', 'Lucia', 'Carmen', 'Paula', 'Maria', 'Elina', 'Anja', 'Ingrid', 'Liv', 'Freja', 'Maja', 'Linnea', 'Sanna', 'Aino', 'Eevi', 'Helmi', 'Abena', 'Adanna', 'Adedayo', 'Adesua', 'Afia', 'Akinyi', 'Alheri', 'Amahle', 'Amaka', 'Amara', 'Anaya', 'Anele', 'Anika', 'Anuli', 'Apio', 'Asanda', 'Asmara', 'Ayaan', 'Ayanda', 'Ayoka', 'Azara', 'Baraka', 'Binta', 'Bolanle', 'Bukola', 'Busisiwe', 'Chiamaka', 'Chibuzo', 'Chidimma', 'Chika', 'Chinelo', 'Chinenye', 'Chioma', 'Chisom', 'Deka', 'Ebele', 'Ebuka', 'Efe', 'Efua', 'Ekua', 'Eloho', 'Enitan', 'Eshe', 'Esinam', 'Ezinne', 'Faduma', 'Fikile', 'Folake', 'Funke', 'Hadiza', 'Halima', 'Ijeoma', 'Imani', 'Iniobong', 'Ireti', 'Itumeleng', 'Ivie', 'Jendayi', 'Jumoke', 'Kafayat', 'Kamsiyochukwu', 'Kehinde', 'Kemi', 'Lerato', 'Lindiwe', 'Makena', 'Malaika', 'Mandisa', 'Mapaseka', 'Mariama', 'Moloko', 'Mpho', 'Mubarakah', 'Nandi', 'Nana', 'Ndidi', 'Nkechi', 'Nkiru', 'Nneka', 'Nthabiseng', 'Ntombezinhle', 'Nyasha', 'Nyauma', 'Nyeleti', 'Nzinga', 'Obianuju', 'Olabisi', 'Omolara', 'Onyekachi', 'Oreoluwa', 'Osas', 'Oyinkansola', 'Phumzile', 'Rashida', 'Rudo', 'Rufaro', 'Sade', 'Siphesihle', 'Thandeka', 'Tumelo', 'Yewande', 'Zawadi'
];

export const lastNames = [
  'Smith', 'Rossi', 'Yamamoto', 'Dubois', 'Kowalski', 'Ivanov', 'Kim', 'Garcia', 'Cohen', 'Haddad', 'Novak', 'Petrov', 'Silva', 'Andersson', 'Jensen', 'Nowak', 'Popescu', 'Hussein', 'Nguyen', 'Patel', 'Fernandez', 'Ahmed', 'Horvath', 'Dimitrov', 'Costa', 'Lefevre', 'Sato', 'Schmitt', 'OConnor', 'Caruso', 'Bianchi', 'Zhang', 'Tanaka', 'Pereira', 'Ali', 'Dimitriou', 'Mammadov', 'Laurent', 'Nielsen', 'Ionescu', 'Baranov', 'MacLeod', 'Tadesse', 'Choudhury', 'Gorski', 'Dlamini', 'Shrestha', 'Reddy', 'Martins', 'Moya', 'Sokolov', 'Wang', 'Sanchez', 'Omondi', 'Sousa', 'Gruber', 'Batista', 'Romero', 'Bakshi', 'Abdi', 'Nascimento', 'Salazar', 'Hoxha', 'Farah', 'Rahman', 'Morales', 'Antunes', 'Bekele', 'Jara', 'Carvalho', 'Nazarov', 'Hakim', 'Georgiou', 'Bashir', 'Duarte', 'Almeida', 'Aziz', 'Okeke', 'Marinov', 'Farouk', 'Delacruz', 'Tan', 'Escobar', 'Villanueva', 'Barros', 'Qureshi', 'Bernal', 'Varga', 'Tavares', 'Mbatha', 'Kalinina', 'Torres', 'Okafor', 'Mensah', 'Abebe', 'Balogun', 'Kabore', 'Toure', 'Ngugi', 'Chilombo', 'Ndlovu', 'Abiola', 'Osei', 'Chirwa', 'Nkosi', 'Zuberi', 'Mutiso', 'Kamara', 'Adegoke', 'Bekele', 'Mugisha', 'Eyob', 'Okechukwu', 'Moyo', 'Bongani', 'Bah', 'Obasi', 'Maiga', 'Onwudiwe', 'Sibanda', 'Adesina', 'Juma', 'Nwosu', 'Ntuli', 'Mekonnen', 'Saidu', 'Eze', 'Odinga', 'Kabongo', 'Chisom', 'Tembo', 'Afolayan', 'Ncube', 'Obeng', 'Gebre', 'Okonkwo', 'Koffi', 'Mambwe', 'Ajayi', 'Mpofu', 'Ayodele', 'Koopman', 'Visser', 'Jansen', 'Bakker', 'Hoekstra', 'Kok', 'Smit', 'Bos', 'Bosman', 'Vermeulen', 'Hendriks', 'Prins', 'Willems', 'Blom', 'Groen', 'Kuipers', 'Scholten', 'Vink', 'Timmermans'
]; 